env: docker
http:
  host: 0.0.0.0
  port: 8000
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    user:
      driver: sqlite
      # 使用 WAL 模式支持更好的并发访问，busy_timeout 设置等待锁的超时时间
      dsn: storage/pvesphere-test.db?_busy_timeout=5000&_journal_mode=WAL
  #    user:
  #      driver: mysql
  #      dsn: root:123456@tcp(127.0.0.1:3380)/user?charset=utf8mb4&parseTime=True&loc=Local
  #    user:
  #      driver: postgres
  #      dsn: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai
  # redis:
  #   addr: cache-redis:6379
  #   password: ""
  #   db: 0
  #   read_timeout: 0.2s
  #   write_timeout: 0.2s
  # mongo:
  #   uri: mongodb://root:123456@localhost:27017
log:
  log_level: info
  mode: both               #  file or console or both
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

