env: docker
http:
  host: 0.0.0.0
  port: 8000
security:
  api_sign:
    app_key: PveSphere@456
    app_security: PveSphere@456
  jwt:
    key: QQYnRFerJTSEcrfB8123w8prOaObmrh8
data:
  db:
    user:
      driver: sqlite
      dsn: storage/pvesphere-prod.db?_busy_timeout=5000&_journal_mode=WAL
log:
  log_level: info
  mode: both
  encoding: console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true